services:
  - type: web
    name: maha-kumbh-mela-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: ENCRYPTION_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false

  - type: static
    name: maha-kumbh-mela-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
